source "https://rubygems.org"

gem "jekyll"
gem "jekyll-paginate"
gem "jekyll-gist"
gem "jekyll-sitemap"
gem "jekyll-feed"
gem "jemoji"
gem "jekyll-include-cache"
gem "kramdown"
gem "rouge"
gem "webrick", "~> 1.7"
