name: Convert BibTeX to YAML

on:
  push:
    branches: [ "main" ]
    paths:
      - 'assets/services.bib'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11.13'
      - name: Install dependencies
        run: pip install bibtexparser pyyaml argparse tqdm
      - name: Convert bibtex to yaml
        run: python ./assets/bib2yml.py --bibtex_fp ./assets/services.bib
      - name: Commit changes
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add _data/service_auto.yml
          git commit -m "Auto-update service.yml from bib (trigger: ${{ github.sha }})" || echo "No changes"
          git push